server:
  port: 8082

spring:
  application:
    name: transaction-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Use StringSerializer for keys datatype for key is string
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # Use JsonConfig for value datatype for value is object
    template:
      default-topic: transaction-events

  datasource:
    url: jdbc:h2:mem:transactiondb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true