server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:

        # ? User Auth (Signup/Login)
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        # ? User Service (Get user info, etc.)
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        # ? Transaction Service
        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/transactions/**

        # ? Reward Service
        - id: reward-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/rewards/**

        # ? Notification Service
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notifications/**


  jwt:
    secret: my-super-secret-key-that-you-never-share


logging:
  level:
    org.springframework.cloud.gateway: DEBUG